driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true
  data_bags_path: "test/fixtures/data_bags"

platforms:
  - name: centos-7.2

suites:
  - name: client
    run_list:
      - recipe[chef-splunk::default]
      - recipe[test::default]
    attributes:
      dev_mode: true
      server:
        runasroot: false
      accept_license: true
      splunk:
        accept_license: true
        indexers_group1:
          splunk_servers: '192.168.10.1:9997, 192.168.10.2:9997, 192.168.10.3:9997'
          outputs_conf:
            sslCommonNameToCheck: sslCommonName
            sslCertPath: $SPLUNK_HOME/etc/certs/cert.pem
            sslPassword: password
            sslRootCAPath: $SPLUNK_HOME/etc/certs/cacert.pem
            sslVerifyServerCert: false
        inputs_conf:
          host: localhost
          ports:
            - port_num: 123123
              config:
                connection_host: dns
                sourcetype: syslog
                source: tcp:123123
