driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true
  data_bags_path: "test/fixtures/data_bags"

platforms:
  - name: centos-7.2

suites:
  - name: client
    run_list:
      - recipe[chef-splunk::default]
      - recipe[test::default]
    attributes:
      dev_mode: true
      splunk:
        accept_license: true
